### ISSUE TITLE
Creación de Demostración del Proyecto en video

### ISSUE THREAD

**Issue by Pamela198713** [abelardog/bootcampar#137]
Encargada de redacción: Pilotti Pamela Sol
Encargado de Grabar la pantalla: celeste esquivel
Encargada de narración: Leonardo Vivas

**Comment by Pamela198713** [comment]
Dejamos aquí tambien el enlace a la presentación, pero ya esta subido en la documentacion del proyecto. https://drive.google.com/file/d/13RSPGsV1xrTCGOhOpbt_1p8uzzarCEzB/view?usp=sharing

**Comment by Pamela198713** [comment]
Se deja a continuación el link de la presentación: https://drive.google.com/file/d/1Vh5k2U7IZW36KHvUsbqYsCwuzqwLTipP/view

**Comment by facumd** [comment]
![bootcampar-sprint-1-part1](https://github.com/abelardog/bootcampar/assets/95236196/f0d99ca6-3a45-4207-88e3-76efe493ee48)
![bootcampar-sprint-1-part2](https://github.com/abelardog/bootcampar/assets/95236196/dac52ec5-ce01-4f6b-af26-22221ba73aa2)
![bootcampar-sprint-1-part3](https://github.com/abelardog/bootcampar/assets/95236196/f15750de-0465-4fff-9004-b2a3ce0cdb4f)
