### ISSUE TITLE
#TK84 Implementar cursos inscriptos

### ISSUE THREAD

**Issue by rpgrca** [abelardog/bootcampar#207]
Al presionar los botones de izquierda y derecha debe mostrar el curso anterior y el curso siguiente entre los que se haya anotado (sin importar si son favoritos o no).

![image](https://github.com/abelardog/bootcampar/assets/15602473/68b12d44-0ef1-4ecb-ac83-d99a1c584c85)

**Comment by rpgrca** [comment]
Se habló en la weekly, borrar eso.

**Comment by facumd** [comment]
Nuevo diseño Perfil:

![Image](https://github.com/abelardog/bootcampar/assets/95236196/e841f31f-eaaa-430f-8216-3ebccfa6e90e)

Ajusto botones para que concuerden con login y registro y me fijo que no verifico que no hay warnings:

![Image](https://github.com/abelardog/bootcampar/assets/95236196/13f06bb5-9df6-4068-a6b8-fcbfc0d28f81)
