### ISSUE TITLE
#TK103 Agregar nuevos  modelos e interfaces a diagrama de clases

### ISSUE THREAD

**Issue by rpgrca** [abelardog/bootcampar#228]
Hasta ahora se agregaron varias interfaces y clases que no estaban en el diagrama de clases original, agregarlas.

**Comment by facumd** [comment]
![diagrama-de-clases-bootcampar](https://github.com/abelardog/bootcampar/assets/95236196/f8bb1efb-527c-41ae-b069-54aeab4ca5e7)

@rpgrca Agregué unos métodos que no estaban contemplados, más lo que hablamos la otra vez de la img para el curso... Una duda en el modelo tenemos una propiedad privada de `isFavourite` (escrita como isFavorite), no sabía si agregarla como atributo al diagrama de clases, ya que también la tenemos en inscripción, debe ser esto ante la duda si se puede calificar el curso como favorito una vez inscripto o no, o si solo se puede calificar una vez el usuario a clickeado en "inscribirse".

Por otro lado, creo saber como se representan las interfaces en el diagrama, pero no se como indicar cuales clases las usan o que modelos faltan agregar. De las nueve tablas que tenemos hay 8 modelos, ya que categorización no tiene su propio modelo (aún?). La clase database es quien usa la interface de IDatabase, y luego los demás IWrappers son utilizados entre ellos o apuntan al mismo fin de esta clase. Espero respuesta y voy a seguir viendo y analizando el vid de refactoreo a la BD para pasar a los de pruebas unitarias e ir cumpliendo mis otras tasks.

**Comment by rpgrca** [comment]
> ![Image](https://user-images.githubusercontent.com/95236196/274037738-f8febdd8-4bc1-458d-82d7-f6f14aee5f40.png)
> 
> @rpgrca Agregué unos métodos que no estaban contemplados, más lo que hablamos la otra vez de la img para el curso... Una duda en el modelo tenemos una propiedad privada de `isFavourite` (escrita como isFavorite), no sabía si agregarla como atributo al diagrama de clases, ya que también la tenemos en inscripción, debe ser esto ante la duda si se puede calificar el curso como favorito una vez inscripto o no, o si solo se puede calificar una vez el usuario a clickeado en "inscribirse".

Ah, me hubieses pedido el link y te lo shareaba para que no tengas que hacerlo todo de cero, jajajaja El isFavorite en Curso está mal, va en inscripción (porque el estudiante define si le gusta o no y es único para cada estudiante, y solamente los estudiantes inscriptos en el curso pueden opinar, en Curso sería favorito para todos incluso para los que no están inscriptos).

> 
> Por otro lado, creo saber como se representan las interfaces en el diagrama, pero no se como indicar cuales clases las usan o que modelos faltan agregar. De las nueve tablas que tenemos hay 8 modelos, ya que categorización no tiene su propio modelo (aún?). La clase database es quien usa la interface de IDatabase, y luego los demás IWrappers son utilizados entre ellos o apuntan al mismo fin de esta clase. Espero respuesta y voy a seguir viendo y analizando el vid de refactoreo a la BD para pasar a los de pruebas unitarias e ir cumpliendo mis otras tasks.
> 
En los diagramas de clases las clases abstractas y creo que las interfaces se marcan con el nombre de la clase en itálica. Nosotros la única interfaz que usamos en el modelo es Serializable que es de sistema (tal vez la cambiemos a Parcelable pero no estoy seguro aún) y creo que esa no se tiene que marcar (porque si no tendríamos que marcar la herencia a Object que tienen todos los modelos por defecto). Habría que agregar lo de IDatabase, ICursorWrapper, ISQLiteDatabaseWrapper y las clases que las implementan, sí, también LogicServices y vincularlas con las flechas de composición. Sin embargo no me gusta mucho porque IDatabase va a quedar como un rectángulo enorme con 40 métodos. Posiblemente separemos la de Database en varias clases más chicas y que por composición use a todas pero como no están terminados todos los modelos ni los métodos todavía no estoy seguro.

**Comment by facumd** [comment]
jajajaja nooo esta bien así! mejor para practicar el noble drawio jaja (ahí subí el file también). Perfecto, corrijo entonces los favourites y lo subo en un rato. Por último aguanto un toque hasta que separemos IDatabase y veamos nuevos métodos.
