### ISSUE TITLE
#TK01 Crear listado de cursos disponibles en el sistema accesible para invitados

### ISSUE THREAD

**Issue by rpgrca** [abelardog/bootcampar#27]

**Comment by rpgrca** [comment]
Hay que armar la actividad del listado para la maquetación

**Comment by celesteeg** [comment]
![Image](https://github.com/abelardog/bootcampar/assets/99212576/d4a2f520-193f-4b48-87ae-d2164d240846)

**Comment by rpgrca** [comment]
Solo muestra los nuevos.
