### ISSUE TITLE
#TK04 Crear maqueta y actividad para recuperar la clave

### ISSUE THREAD

**Issue by rpgrca** [abelardog/bootcampar#30]

**Comment by celesteeg** [comment]
![Image](https://github.com/abelardog/bootcampar/assets/99212576/9642f007-4405-44bd-8d2a-308fb15ead3b)

**Comment by rpgrca** [comment]
![image](https://github.com/abelardog/bootcampar/assets/15602473/0be17908-4631-4678-9e73-fcad9c353021)
