### ISSUE TITLE
#TK05 Crear maqueta y actividad de búsqueda de cursos simple por nombre

### ISSUE THREAD

**Issue by rpgrca** [abelardog/bootcampar#31]

**Comment by celesteeg** [comment]
![Image](https://github.com/abelardog/bootcampar/assets/99212576/e0eb7641-0220-4e2c-bfd8-47eef14e6e2b)

**Comment by rpgrca** [comment]
![image](https://github.com/abelardog/bootcampar/assets/15602473/f04cc01f-cc21-407b-8006-b7534520ed1b)

![image](https://github.com/abelardog/bootcampar/assets/15602473/17568121-21fb-43a7-939a-b8228c3e8665)

Listo! Aunque hay que quitar el help porque abajo entran 5 íconos como máximo, queda para el próximo sprint.
