### ISSUE TITLE
#TK135 Video de accesibilidad

### ISSUE THREAD

**Issue by rpgrca** [abelardog/bootcampar#350]
Hay que hacer un video de 1 minuto sobre cómo aplicamos la accessibilidad en nuestro proyecto, cambios antes y después.

**Comment by rpgrca** [comment]
Hay que agregar el link a la sección de Testing de la Wiki.

**Comment by rpgrca** [comment]
![image](https://github.com/abelardog/bootcampar/assets/15602473/d561a8f1-ead0-45a0-a6cf-35b7bc48e458)

**Comment by rpgrca** [comment]
Se puede crear un documento en la Wiki con imágenes de antes y después y la explicación escrita, y luego se graban leyéndo la explicación, tiene que ser video pero creo que se pueden poner imágenes porque el ejemplo que mostró era con imágenes fijas.

**Comment by LuciaL152** [comment]
https://github.com/abelardog/bootcampar/assets/106400404/55dc8fba-fe8e-4ad6-9138-37010cfa0a41

**Comment by LuciaL152** [comment]
https://docs.google.com/document/d/14__rydrO4QWwW4L5MpXTKMKtwBRhB0VxK8VE32cNbxY/edit?usp=sharing

**Comment by LuciaL152** [comment]
LINK DEL VIDEO: https://drive.google.com/file/d/1UBmgxJaweK45o-auCtTZI4ZeNC5Ku8I2/view?usp=sharing[](url)
