### ISSUE TITLE
#TK136 Video de Selenium

### ISSUE THREAD

**Issue by rpgrca** [abelardog/bootcampar#351]
Hay que armar un video por grupo de testing de Selenium a una página web.

**Comment by rpgrca** [comment]
Hay que agregar el link a la sección de Testing de la Wiki

**Comment by rpgrca** [comment]
![image](https://github.com/abelardog/bootcampar/assets/15602473/2c82c5b9-4681-4483-831b-29e501d83daa)

**Comment by rpgrca** [comment]
https://www.selenium.dev/selenium-ide/

**Comment by facumd** [comment]
La automatización con selenium debe ser sobre cualquier página web? Es decir no necesariamente sobre el proyecto? Ya que vi que para testear automatizar mobile usan appium en conjunto con selenium al parecer, no pude asistir a la clase de de ayer (martes) asi que tengo esa duda, sin embargo ya bajé el ide de selenium y me estuve familiarizando

**Comment by facumd** [comment]
![Image](https://github.com/abelardog/bootcampar/assets/95236196/88be57c5-4375-4223-a0ac-a079982db0cf)

Estuve testeando sobre saucedemo.com, bastante intuitiva la extensión de chrome, mañana por la mañana hago el ejemplo del material obligatorio tal cual con Pame.

**Comment by facumd** [comment]
Hecho! https://drive.google.com/file/d/1AyzbTj5fFmB_bw6R2s7YSEuX4gBGzk-O/view?usp=drive_link
