### ISSUE TITLE
#TK14 Crear un Diagrama de Clases

### ISSUE THREAD

**Issue by LuciaL152** [abelardog/bootcampar#36]

**Comment by rpgrca** [comment]
Solamente diagrama de clases en esta tarea

**Comment by rpgrca** [comment]
![image](https://github.com/abelardog/bootcampar/assets/15602473/ccdac4cf-60af-4916-ae6d-8fc3deef4438)

**Comment by rpgrca** [comment]
Faltan los métodos todavía

**Comment by rpgrca** [comment]
![diagrama-de-clases](https://github.com/abelardog/bootcampar/assets/15602473/b2915581-4321-4268-b230-e1e9b04bdca0)

Listo!
