### ISSUE TITLE
#TK11 Agregar actividad de descripción del curso

### ISSUE THREAD

**Issue by rpgrca** [abelardog/bootcampar#41]

**Comment by facumd** [comment]
Me encargaré en breve

**Comment by facumd** [comment]
![86a0e955-164e-4aab-a51e-459d8028e388](https://github.com/abelardog/bootcampar/assets/95236196/dae72384-c93f-420f-8f20-192813b229c9)
![a854ee9e-1893-4111-97da-bce061b2b945](https://github.com/abelardog/bootcampar/assets/95236196/fd96ef09-7823-48f3-90a3-07a8100020a3)
![a5aa74cf-09fa-4a3d-8eb5-b0fd6bd6e35f](https://github.com/abelardog/bootcampar/assets/95236196/2e19c749-8970-4859-b88d-e327fae49d6a)

**Comment by rpgrca** [comment]
Listo!
