### ISSUE TITLE
#TK24 Caso de uso Listado de cursos

### ISSUE THREAD

**Issue by rpgrca** [abelardog/bootcampar#54]

**Comment by LuciaL152** [comment]
![image](https://github.com/abelardog/bootcampar/assets/106400404/ac3a7734-ccca-4572-99a6-dbd12caf11c0)

**Comment by LuciaL152** [comment]
![CasoDeUsoListadoDeCursos drawio](https://github.com/abelardog/bootcampar/assets/106400404/81574727-49ab-4b4f-a4ae-fa5468e165a2)

**Comment by LuciaL152** [comment]
![CasoDeUsoListadoDeCursos2](https://github.com/abelardog/bootcampar/assets/106400404/2efdea97-cc4c-436d-bc89-7e28f2707f16)
