### ISSUE TITLE
#TK27 Caso de uso Marcar como favorito

### ISSUE THREAD

**Issue by rpgrca** [abelardog/bootcampar#57]

**Comment by Pamela198713** [comment]
[Caso de uso Marcar como Favorito.pdf](https://github.com/abelardog/bootcampar/files/12641020/Caso.de.uso.Marcar.como.Favorito.pdf)

**Comment by LuciaL152** [comment]
![Untitled Diagram drawio](https://github.com/abelardog/bootcampar/assets/106400404/e016112d-089a-4d81-93d4-1bfd01b5ed17)
