### ISSUE TITLE
#TK30 Realizar 3 casos de prueba para la app

### ISSUE THREAD

**Issue by facumd** [abelardog/bootcampar#93]
- [x] Caso de Prueba 1
- [x] Caso de Prueba 2
- [x] Caso de Prueba 3

https://docs.google.com/document/d/1XDzkb0vxTCvlezZC16IP7lPqosnpx9DNRMXKyDA8RMw/edit (Con tabla para completar)

**Comment by facumd** [comment]
Caso de Prueba a realizar sugerido por @celesteeg Registro:

CP1: trazabilidad - Ingresar sin datos de entrada y dar click en registrarse -> Results: Msj que muetra la app en el toast: "Por favor complete todos los datos correctamente"

CP2: trazabilidad - Ingresar contraseñas que no son iguales y dar click en registrarse -> Results: Msj que muetra la app en el toast: "Las contraseñas ingresadas no concuerdan"

CP3: trazabilidad - Completar todos los datos correctamente y clickear en registrarse -> Results; Msj que muetra la app en el toast: "Registración exitosa!" & Redirige al usuario a la actividad del home

> A tener en cuenta que una de las precondiciones es que el dispositivo esté conectado a internet y la app esté en production

> La prioridades son irrelevantes ya que aun no vimos esos temas aun, pueden especificarse con mayor acierto en un futuro como dijo la profesora

**Comment by facumd** [comment]
![Image](https://github.com/abelardog/bootcampar/assets/95236196/6242fba3-cb6a-4ebd-a840-a6e52722c5f4)

![Image](https://github.com/abelardog/bootcampar/assets/95236196/27f1d5f3-347c-4df1-9770-192aec35b67b)

![Image](https://github.com/abelardog/bootcampar/assets/95236196/cb7acb70-8c1a-4e1d-87b4-bb06a52f120a)

**Comment by facumd** [comment]
![Image](https://github.com/abelardog/bootcampar/assets/95236196/bf1f01ee-4004-4632-85fc-aa7aff2386ec)

>Creada la tabla para agregar los casos de prueba

**Comment by facumd** [comment]
![Image](https://github.com/abelardog/bootcampar/assets/95236196/56ddc7d1-12b6-4fa2-8921-9aa1194510a2)

**Comment by rpgrca** [comment]
La imagen es muy pequeña, no se ve

**Comment by facumd** [comment]
![Image](https://github.com/abelardog/bootcampar/assets/95236196/6126d3d7-d78b-4dd3-ac0c-e55754efcaac)

**Comment by rpgrca** [comment]
Está perfecto! Hice un par de modificaciones (le puse los datos que se usan para la prueba del CP2, puse itálicas a toast y puse mensaje en lugar de msg. Al documento en doc habría que bajarlo a un pdf llamado casos-de-pruebas-para-registracion.pdf y subirlo dentro de docs, también agregarlo en la Wiki.

**Comment by rpgrca** [comment]
![image](https://github.com/abelardog/bootcampar/assets/15602473/7501c915-2b5e-4570-8a80-adb852d8e902)

Dijeron que no hay que armar la última columna....

**Comment by facumd** [comment]
![Image](https://github.com/abelardog/bootcampar/assets/95236196/08b217a7-504a-427a-814e-8a55233eab58)


Quité la ultima columna, en un rato subo la doc en pdf y lo agrego a la wiki en formato .md
