### ISSUE TITLE
#TK31 Crear actividades de la app

### ISSUE THREAD

**Issue by facumd** [abelardog/bootcampar#94]
- [x] #28 
- [x] #95
- [x] #97
- [x] #30 
- [x] #103
- [x] #31 
- [x] #100
- [x] #41 
- [x] #108 
- [x] #110

![Image](https://github.com/abelardog/bootcampar/assets/95236196/9fdac492-ddd4-4240-9123-1e6a567cdf9b)

[Link al Documento Figma](https://www.figma.com/file/8UGS2u1XMBbejPGKUqwqHW/Untitled?type=design&node-id=0-1&mode=design)

**Comment by rpgrca** [comment]
No tenemos historia de usuario para el login pero ya hice la tarea.

**Comment by Pamela198713** [comment]
Arma la historia de usuario y queda completa

**Comment by rpgrca** [comment]
Hay que agregar una de contacto, me encargo de ella.

**Comment by rpgrca** [comment]
Todas terminadas!

**Comment by facumd** [comment]
A continuación dejo imgs de las 13 pantallas que tenemos hasta ahora y que serán subidas al IEEE830:

![Image](https://github.com/abelardog/bootcampar/assets/95236196/d3bd6bfa-8cf7-45ef-ba3a-da0a1362e4d1)
![Image](https://github.com/abelardog/bootcampar/assets/95236196/b76050d3-6dc2-4ea5-bc30-337cec022b47)
![Image](https://github.com/abelardog/bootcampar/assets/95236196/a5b21fd3-1a7f-4ca4-9a86-37e95fece689)
![Image](https://github.com/abelardog/bootcampar/assets/95236196/f63d3692-3e29-4336-87fe-b7100bac2ca8)
![Image](https://github.com/abelardog/bootcampar/assets/95236196/69b98b46-cc14-452d-acb7-4d4c1f2a28ee)
![Image](https://github.com/abelardog/bootcampar/assets/95236196/66b19dac-c714-4ff2-a187-e41f8aa95f15)
![Image](https://github.com/abelardog/bootcampar/assets/95236196/b7d5abfb-0286-4034-b8d1-a9fc3b3a5711)
![Image](https://github.com/abelardog/bootcampar/assets/95236196/850d26ac-addc-4bcc-97bf-229ee0673a1a)
![Image](https://github.com/abelardog/bootcampar/assets/95236196/46dbbb1d-6973-4943-ac3e-137d37076dd4)
![Image](https://github.com/abelardog/bootcampar/assets/95236196/284c7b7e-5ffb-40bc-8b4b-79da8204687f)
![Image](https://github.com/abelardog/bootcampar/assets/95236196/540db45a-0212-49a2-933f-80e16099c8c7)
![Image](https://github.com/abelardog/bootcampar/assets/95236196/e7c3a3fe-f450-4b6c-a64b-400be08938a1)
![Image](https://github.com/abelardog/bootcampar/assets/95236196/be78e4c0-3b82-48b4-98e8-8914d617126c)
